# Generated by Django 3.2 on 2023-07-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230714_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='precontent',
            field=models.TextField(default='precontent'),
            preserve_default=False,
        ),
    ]
