# Generated by Django 3.2 on 2023-08-12 14:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_precontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='advertising',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Adv'),
        ),
    ]
